[package]
name = "u3d"
version = "0.1.0"
authors = ["Kristóf Ralovich <tade60@freemail.hu>"]
edition = "2024"
license = "MIT"
description = "Rust crate implementation of the U3D (Universal 3D, ECMA-363) file format, most commonly found embedded in 3D PDFs."
repository = "https://github.com/ralovich/u3d"

[dependencies]
byteorder = "1"
log = "0.4"
measure_time = "0.9.0"
num_enum = "0.7.6"
bitstream-io = "4.10"

[workspace]
members = ["tools"]
exclude = ["fuzz"]

[profile.release]
lto = "thin"

[profile.reldeb]
inherits = "release"
lto = "off"
debug = true