#!/usr/bin/env python3
# -*- mode: python; coding: utf-8-unix -*-
#
# SPDX-License-Identifier: MIT
#
# SPDX-FileCopyrightText: Copyright Kristóf Ralovich (C) 2025-2026. All rights reserved.

# python3 -m venv .venv
# .venv/bin/python -m pip freeze > requirements.txt
# .venv/bin/python -m pip install -r requirements.txt
# sudo apt install ugrep zstd
# RUST_LOG=trace RUST_BACKTRACE=1 DESCRIBE=~/dev/pdf3d/u3d-rs/target/reldeb/u3d-describe INPUT=list_all.txt time ./u3d_describe_mt

import os
import subprocess
import multiprocessing as mp
import time
import datetime
import tqdm

DESCRIBE = os.getenv("DESCRIBE")
# ls -1S *.u3d > list_all.txt
INPUT = os.getenv("INPUT")
parallel = True
#parallel = False
outlog='review_summary_u3d.txt'

def describe_one_file(file_path):
    file_path = file_path.strip()
    log_path = os.path.splitext(file_path)[0]+'.txt'

    cmd = f'{DESCRIBE} \"{file_path}\" 2>&1 | zstd -zfqo \"logs/{log_path}.zst\" ; exit ${{PIPESTATUS[0]}}'
    #cmd = f'{DESCRIBE} \"{file_path}\" > \"logs/{log_path}\" 2>&1'
    #print(cmd)
    start_time = time.time()
    cmd_rv = subprocess.run(["bash", "-c", f'{cmd}'])
    run_time = (time.time() - start_time)*1000

    ver_major = '?'
    ver_minor = '?'
    num_blocks = '?'
    num_failed = '?'
    num_unknown = '?'
    
    rv = subprocess.run(["ugrep", "-z", 'U3D file version ', f'logs/{log_path}.zst'], capture_output = True, check = False)
    if rv.returncode == 0:
        #print(rv.stdout)
        ver_major = rv.stdout.decode('UTF-8').strip().split()[6]
        #print(ver_major)
        ver_minor = rv.stdout.decode('UTF-8').strip().split()[7]

    rv = subprocess.run(["ugrep", "-z", 'U3D parsed ', f'logs/{log_path}.zst'], capture_output = True, check = False)
    if rv.returncode == 0:
        #print(rv.stdout)
        num_blocks = rv.stdout.decode('UTF-8').strip().split()[5]
        num_blocks = int(num_blocks)
        #print(num_blocks)
        num_failed = rv.stdout.decode('UTF-8').strip().split()[8]
        num_failed = int(num_failed)
        #print(num_failed)
        num_unknown = rv.stdout.decode('UTF-8').strip().split()[10]
        num_unknown = int(num_unknown)

    return (file_path, run_time, cmd_rv.returncode, ver_major, ver_minor, num_blocks, num_failed, num_unknown)


if __name__ == '__main__':
    lines=[]
    with open(INPUT, 'r') as file:
        lines = file.readlines()
        lines = [l.strip('\n\r') for l in lines]
    #lines=lines[:1]
    print(f'Found {len(lines)} cases in \"{INPUT}\"')

    os.makedirs("logs", exist_ok = True)

    if parallel:
        ncpus = mp.cpu_count()
        print(f'Using {ncpus} concurrent processes')

        cases = lines
        print(f'Generated {len(cases)} work items')

        # with mp.Pool(ncpus) as p:
        #     results = p.map(describe_one_file, cases)
        with mp.Pool(ncpus) as p, tqdm.tqdm(total=len(cases)) as pbar:
            results = []
            for r in p.imap_unordered(describe_one_file, cases):
                pbar.update()
                #pbar.refresh()
                results.append(r)
            pbar.close()
            p.close()
            p.join()
        print('')
    else:
        results = []
        for line in tqdm.tqdm(lines):
            file_name = line.strip()
            #print(file_name)
            r = describe_one_file(file_name)
            results.append(r)
        assert(len(lines) == len(results))

    with open(outlog, 'w') as rs:
        now = str(datetime.datetime.now())
        empty = " "
        rs.write(f'{empty:92}\tcmd_rv\tver_maj\tver_min\tblocks\tfailed\tunimpl\n')
        print(f"{empty:92}\tcmd_rv\tver_maj\tver_min\tblocks\tfailed\tunimpl\truntime_ms")
        print(now)
        ncases = len(lines)
        stats = {}
        for item in lines:
            for result in results:
                (file_path, run_time, cmd_rv, ver_major, ver_minor, num_blocks, num_failed, num_unknown) = result
                if item != file_path:
                    continue
                rs.write(f'{file_path:92}\t{cmd_rv}\t{ver_major}\t{ver_minor}\t{num_blocks}\t{num_failed}\t{num_unknown}\n')
                print(f'{file_path:92}\t{cmd_rv}\t{ver_major}\t{ver_minor}\t{num_blocks}\t{num_failed}\t{num_unknown}\t{run_time:.1f}', end='\n')
                sec_id = 0 # crash
                if not sec_id in stats:
                    stats[sec_id] = 0
                if cmd_rv == 0:
                    stats[sec_id] += 1
                sec_id = 1 # any failed blocks?
                if not sec_id in stats:
                    stats[sec_id] = 0
                if num_failed == 0:
                    stats[sec_id] += 1
                sec_id = 2 # any unimplemented blocks?
                if not sec_id in stats:
                    stats[sec_id] = 0
                if num_unknown == 0:
                    stats[sec_id] += 1
        print(f'\n\nNO CRASH PASS: {stats[0]:4}/{ncases:4} ({stats[0]/ncases*100.0:.0f}%)\t\tFAIL: {ncases-stats[0]:4}/{ncases:4} ({(ncases-stats[0])/ncases*100.0:.0f}%)')
        print(f'FAILED B PASS: {stats[1]:4}/{ncases:4} ({stats[1]/ncases*100.0:.0f}%)\t\tFAIL: {ncases-stats[1]:4}/{ncases:4} ({(ncases-stats[1])/ncases*100.0:.0f}%)')
        print(f'UNIMPL B PASS: {stats[2]:4}/{ncases:4} ({stats[2]/ncases*100.0:.0f}%)\t\tFAIL: {ncases-stats[2]:4}/{ncases:4} ({(ncases-stats[2])/ncases*100.0:.0f}%)\n\n')
        rs.write(f'\n\nNO CRASH PASS: {stats[0]:4}/{ncases:4} ({stats[0]/ncases*100.0:.0f}%)\t\tFAIL: {ncases-stats[0]:4}/{ncases:4} ({(ncases-stats[0])/ncases*100.0:.0f}%)\n')
        rs.write(f'FAILED B PASS: {stats[1]:4}/{ncases:4} ({stats[1]/ncases*100.0:.0f}%)\t\tFAIL: {ncases-stats[1]:4}/{ncases:4} ({(ncases-stats[1])/ncases*100.0:.0f}%)\n')
        rs.write(f'UNIMPL B PASS: {stats[2]:4}/{ncases:4} ({stats[2]/ncases*100.0:.0f}%)\t\tFAIL: {ncases-stats[2]:4}/{ncases:4} ({(ncases-stats[2])/ncases*100.0:.0f}%)\n')


